# Generated by Django 4.1.4 on 2023-01-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobile_phone',
            new_name='phone',
        ),
    ]
