# Generated by Django 4.1.4 on 2023-01-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_market_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='market'),
        ),
    ]
