# Generated by Django 4.1.4 on 2023-02-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_market_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
