# Generated by Django 4.1.4 on 2023-01-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_brand', models.CharField(choices=[('Supermercado', 'market'), ('Restaurant', 'restaurant')], max_length=50)),
                ('contact', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
