# Generated by Django 4.1.4 on 2023-01-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='contact',
            new_name='web',
        ),
    ]
