# Generated by Django 4.1.4 on 2023-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_rename_contact_brand_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='type_brand',
            field=models.CharField(choices=[('Supermercado', 'market'), ('Restaurante', 'restaurant'), ('Emprendimiento', 'entrepreneur')], max_length=50),
        ),
    ]
