# Generated by Django 4.1.4 on 2023-01-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_type_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='type_brand',
            field=models.CharField(choices=[('Supermercado', 'Supermercado'), ('Restaurante', 'Restaurante'), ('Emprendimiento', 'Emprendimiento')], max_length=50),
        ),
    ]
