# Generated by Django 4.1.4 on 2023-01-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brand_type_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
